### ISSUE TITLE
i-tw.org › twpay 掛了

### ISSUE THREAD

**Issue by s793016** [s950449/TWPayQRCodeGenerator#5]
https://i-tw.org/twpay

This Account has been suspended.
[Contact your hosting provider](https://i-tw.org/home/) for more information.

**Comment by s950449** [comment]
Thanks for your reminder. You can use offline mode instead.

**Comment by s950449** [comment]
Fixed in the latest release(2024-01-06 Ver 0.2.0) Closed.
